### ISSUE TITLE
Code wrapped in :nocov: not being ignored

### ISSUE THREAD

**Issue by cpence** [codeclimate/ruby-test-reporter#62] opened 2014-12-18 16:53 UTC
Check out the `#devise_parameter_sanitizer` method in my application controller (l. 136):

<https://codeclimate.com/github/rletters/rletters/ApplicationController>

It's wrapped in `# :nocov:` comments, but still showing red and counting off my coverage percentage.

I do configure SimpleCov myself, but I don't see anything there that should be the cause of the problem:

```
  require 'simplecov'
  require 'codeclimate-test-reporter'
  SimpleCov.formatter = CodeClimate::TestReporter::Formatter

  SimpleCov.start do
    add_filter '/spec/'
    add_filter '/features/'
    add_filter '/config/'
    add_filter '/db/'
    add_filter '/vendor/bundle/'
    add_filter '.haml'
    add_filter '.erb'
    add_filter '.builder'

    # NB: Doesn't matter whether or not the next line is present, still doesn't work
    skip_token CodeClimate::TestReporter.configuration.skip_token
  end
```

Thoughts? Is there a bug here, or am I misconfiguring something?

**Comment by michaelmior** [comment] 2015-01-19 00:14
Seeing the same issue here.

**Comment by calavera** [comment] 2015-01-19 17:45
Interesting. I don't see any reason why simplecov could not be working properly. This might be an issue in the visualization, where `nocov` is represented as red because there is no coverage for that method. I'll open an internal ticket to track this down.

**Comment by michaelmior** [comment] 2015-01-19 18:19
@calavera If it is the visualization, my opinion would be that it would be great to have code marked with `nocov` coloured yellow instead of red (or green).

**Comment by did** [comment] 2015-02-05 11:40
Same problem here: https://codeclimate.com/github/locomotivecms/steam/Locomotive::Steam::Liquid::Tags::Editable::Base (l 78).
One more thing, the results (for instance, the percentage of covered code) I get when I run locally SimpleCov are also different from the one I got in CodeClimate.
But, we've got to keep in mind that the results CodeClimate displays are returned by another service, like Travis CI (in my case). Perhaps, it's related to this but I don't see how. 
Not a big deal...

**Comment by calumhalcrow** [comment] 2015-02-25 02:45
I'm also seeing this [TravisCI](https://travis-ci.org/GovWizely/webservices/builds/52018885) says 100%, Code Climate says 99.63%. Looking at CC's coverage report, I can see that the source files which are missing coverage are the ones that have :nocov: directives.

**Comment by whitelancer** [comment] 2015-03-11 06:46
I'm also experiencing this issue.  I can't seem to figure out whether it's a Simplecov issue or a TestReporter one.  The output from the TestReporter in CircleCI looks different so maybe there's some issue between SimpleCov, CircleCI, and CodeClimate?

**Comment by sometimesfood** [comment] 2015-03-11 09:14
> The output from the TestReporter in CircleCI looks different so maybe there's some issue between SimpleCov, CircleCI, and CodeClimate?

No, I see the same behaviour with Travis+simplecov+codeclimate-test-reporter as well as simplecov+codeclimate-test-reporter.

**Comment by cpence** [comment] 2015-05-21 18:14
Any update on this issue?

**Comment by dimascyriaco** [comment] 2015-07-12 20:49
I having this problem too.
Any news?

**Comment by killthekitten** [comment] 2015-08-02 17:43
+1

**Comment by jordanbsanders** [comment] 2015-09-25 21:29
+1

**Comment by tirdadc** [comment] 2016-05-20 19:30
+1

**Comment by caiosba** [comment] 2016-07-21 20:56
+1

**Comment by BandanaPandey** [comment] 2016-09-16 13:44
I have the same issue, when i run SimpleCov locally the percentage of covered code is different from
the coverage which i got from CodeClimate.
I don't know why this is happening or what the issue is?
Also, I am using Travis CI, so is this happening because of Travis CI?

**Comment by dblandin** [comment] 2016-10-03 16:38
Hey @cpence,

We've made some improvements to the ruby test reporter that should address the inconsistencies you reported.

The new version requires a different invocation style. You can find the upgrade documentation [here](https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions).

Thanks!

**Comment by cpence** [comment] 2016-10-03 19:49
Thanks for this! I can't check whether it resolves my issue for a few days, but I will report back when I'm able.

**Comment by pbrisbin** [comment] 2016-10-18 19:17
Going to go ahead and close, since we believe this is fixed in the new version. Please re-open if this is still an issue. Thanks!

**Closed by pbrisbin** 2016-10-18 19:17 UTC

**Comment by cpence** [comment] 2018-05-19 15:14
There's been a regression on this issue. Check, e.g., this source file: https://codeclimate.com/github/rletters/rletters/app/controllers/errors_controller.rb/source

The `unprocessable` method at the bottom is wrapped in `:nocov:` comments, and not ignored.

I'm using the latest test reporter; see the invocation here: https://github.com/rletters/rletters/blob/master/.travis.yml

**Comment by maxjacobson** [comment] 2018-05-22 14:28
Hi @cpence. Thanks for the nudge. This is on our radar, and is being tracked at: https://github.com/codeclimate/test-reporter/issues/246

**Comment by cpence** [comment] 2018-05-23 02:59
Whoops, sorry to necro an old thread (and repo!). Following at the new issue.
