### ISSUE TITLE
Coverage dffers locally and on CodeClimate

### ISSUE THREAD

**Issue by SergeyKishenin** [codeclimate/ruby-test-reporter#157] opened 2016-11-22 19:16 UTC
Hi,

I'm getting different results locally and on CodeClimate for the same file:

![screenshot from 2016-11-23 00 30 36](https://cloud.githubusercontent.com/assets/512703/20538115/fd5f429e-b119-11e6-974d-4416b9f96339.png)

![screenshot from 2016-11-23 01 11 44](https://cloud.githubusercontent.com/assets/512703/20538116/fd624fac-b119-11e6-98cd-ee121f5c5218.png)

And CodeClimate reports blank lines and `end` statements as uncovered, but locally it's skipped:

![screenshot from 2016-11-23 01 12 08](https://cloud.githubusercontent.com/assets/512703/20538160/2f97e734-b11a-11e6-8a66-7a366f40cc90.png)

We are using `codeclimate-test-reporter` `v1.0.3` and Solano CI Service.

**Comment by bodrovis** [comment] 2016-11-29 17:17
I was having a pretty similar issue, but after adding an after hook into the .travis.yml results seem to be updated propertly

```
after_success:
  - bundle exec codeclimate-test-reporter
```

**Comment by pbrisbin** [comment] 2016-11-29 17:30
@SergeyKishenin would you be able to grab the actual `coverage/.resultset.json` file that Simplecov produces right before you invoke the reporter on CI and compare it to what's produced when you do whatever you do to locally view results?

If they're not the same, then something different in your local vs CI environment is making Simplecov itself behave differently.

If they're identical though, then the problem is either in reporting or rendering.

Sometimes, seeing such a reduction in coverage on Code Climate can be caused by running multiple test suites. It's possible viewing locally will show merged coverage results from all suites, but our reporter is limited in that it will only report the coverage results from the last suite to run.

**Comment by pbrisbin** [comment] 2017-01-04 19:43
I'm going to go ahead and close this as stale. Please re-open if you are still having this issue and are able to provide those additional details. Also note that #162 (now fixed) may also have been causing this.

**Closed by pbrisbin** 2017-01-04 19:43 UTC
