### ISSUE TITLE
Webmock does not recognize my settings or I'm doing something wrong

### ISSUE THREAD

**Issue by mediatainment** [codeclimate/ruby-test-reporter#23] opened 2013-11-21 08:40 UTC
the VERY FIRST line of my spec_helper.rb:

```ruby
if ENV["RAILS_ENV"] == "test" && ENV['CODECLIMATE_REPO_TOKEN']
  WebMock.disable_net_connect!(:allow => "codeclimate.com")
  require "codeclimate-test-reporter"
  CodeClimate::TestReporter.start
end

require 'rubygems'
require 'spork'
... 
```

webmock (1.16.0)
codeclimate-test-reporter (0.2.0)
rails (3.2.14)
Ruby 2

*Error message:*

Coverage = 79.92%. Sending report to https://codeclimate.com for branch tag/codeclimate_webmock... /home/rof/cache/bundler/ruby/2.0.0/gems/webmock-1.16.0/lib/webmock/http_lib_adapters/net_http.rb:114:in `request': Real HTTP connections are disabled. Unregistered request: POST https://codeclimate.com/test_reports with body 'RZn8~^W"Y5-K$;o)I'u8tPO`Y$-7dEWAeAHt	BDPqdgT&&WU[6w(]uUih8.Kl-Ek	4F(+U;&sf<-89#dxN\5_WezlfV7o|mo}wX
_By[u$GWmK[jh$)z&uT\[eMNzNh(9c6(x@U,dpFPA;Y`2~*sLN*;"e]	&SVSuIbT (WebMock::NetConnectNotAllowedError)
oA}t=4MlW'^_A|F6/hH_`.:!VEuOh31vZRvNR$ZTm{AF"k>ftz3~"t\b%J/iT,<C, 	SrYMxo/i>yswrhlA,Omyz}2lO "55`4Qfh
fFDRa$L_N#3%B2pc:[GD|<D~
D:aIQ*
s1rB'&.PK.9mVDhg7y>#f1)G-bRbBgx\L^X5aYY^6`g}*F<L
~1XC]bwdq1}gs~MZ*vi/:|hyfU.fFOZ631!Drs,G 3#7TO@wWk%-MxYaWCs B]wq.Q
qd'0Cw!auW4uuFDNz]_MDH}T;rR<G6Vp
\4n;lGQ#L%'o5j%	LXX_*G\f?aqX
(<vmQbmdQ$e,>$f%!I1)*b=IfKacJ-x$'>x2JSZ!QME-OIxWx$e79Rk`Dt P=	
aU4A43ef?1|bwQQM.">G^sfj,$6?w'	
`Q)i/"<IP?uadFu`%
@9J~5~cbl{h'K1bD,r>J%!di_h1LZ*PVI|G=j'7p7*{`qX%GBi2AO<se9GSv 	7Z*>\F,a3wc7>|_fA?2L#J57oYMj_t}d:J^hR&X)J#`u<]G{BI1C
TgU_+z`l]c}|}>;K#{m--p64{9(]$E>?F[O8;RDqabk+"bx	'	CqmQ&#\`3B!4/nRuf|) fn-W~M;}XGpwX//C6kNY*B!zJ]3G">dz(' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Encoding'=>'gzip', 'Content-Type'=>'application/json', 'User-Agent'=>'Code Climate (Ruby Test Reporter v0.2.0)'}

You can stub this request with the following snippet:

stub_request(:post, "https://codeclimate.com/test_reports").
  with(:body => "\u001F\x8B\b\u00

```

**Comment by denyago** [comment] 2015-12-01 09:21
Just had this issue. Resolved it like this

`Gemfile`
```ruby
group :test do
  # ...

  # Require it explicitly in a spec/support file
  # as it not plays nice with Codeclimate
  gem 'webmock', require: false

  # ...
end
```

`spec/support/webmock.rb` (but could be `spec/rails_helper.rb`)
```ruby
require 'webmock/rspec'

WebMock.disable_net_connect!(allow: 'codeclimate.com')
```

**Comment by dblandin** [comment] 2016-03-08 20:52
Seems like we've narrowed down the cause to webmock setup, so I'm going to go ahead and close this issue.

**Closed by dblandin** 2016-03-08 20:52 UTC
